import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    slug: "midnight-obsession-dress",
    name: "Midnight Obsession Dress",
    price: 89,
    originalPrice: 120,
    category: "dresses",
    images: [
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black"],
    description: "The ultimate power dress. Sculpting bodycon silhouette in premium stretch fabric that moves with your every curve. Mini length, barely-there back.",
    details: ["95% Polyester, 5% Elastane", "Hand wash cold", "Model is 5'9\" wearing size S", "Mini length", "Invisible zip closure"],
    isNew: true,
    isBestSeller: true,
    stockCount: 4,
    rating: 4.9,
    reviewCount: 238,
    tags: ["bodycon", "mini", "black", "night out"],
  },
  {
    id: "2",
    slug: "pink-venom-corset-set",
    name: "Pink Venom Corset Set",
    price: 119,
    category: "sets",
    images: [
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Hot Pink", "Black"],
    description: "Two-piece matching set featuring a boned corset top and high-waisted mini skirt. Statement hot pink in premium satin.",
    details: ["100% Satin", "Dry clean only", "Boned corset structure", "Matching mini skirt included", "Adjustable lacing back"],
    isNew: true,
    isTrending: true,
    stockCount: 6,
    rating: 4.8,
    reviewCount: 156,
    tags: ["corset", "set", "pink", "satin"],
  },
  {
    id: "3",
    slug: "crystal-queen-bodycon",
    name: "Crystal Queen Bodycon",
    price: 135,
    category: "dresses",
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Silver", "Black"],
    description: "Hand-embellished crystal mesh bodycon. Every step is a moment. Fully lined with luxury mesh overlay.",
    details: ["Mesh with crystal embellishments", "Fully lined", "Dry clean only", "Mini length", "Concealed zip"],
    isBestSeller: true,
    isTrending: true,
    stockCount: 3,
    rating: 5.0,
    reviewCount: 89,
    tags: ["crystal", "embellished", "mesh", "silver"],
  },
  {
    id: "4",
    slug: "dark-desire-jumpsuit",
    name: "Dark Desire Jumpsuit",
    price: 99,
    category: "jumpsuits",
    images: [
      "https://images.unsplash.com/photo-1566206091558-7f218b696731?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1529139574466-a303027bc851?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black"],
    description: "Sleek one-piece jumpsuit with plunging neckline and wide-leg silhouette. Effortlessly elevated.",
    details: ["92% Polyester, 8% Spandex", "Machine wash cold", "Wide leg cut", "Plunge neckline", "Belt included"],
    isNew: true,
    rating: 4.7,
    reviewCount: 112,
    tags: ["jumpsuit", "wide-leg", "black", "plunge"],
  },
  {
    id: "5",
    slug: "velvet-noir-mini",
    name: "Velvet Noir Mini",
    price: 95,
    originalPrice: 130,
    category: "dresses",
    images: [
      "https://images.unsplash.com/photo-1496747611176-887b1138d930?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Deep Plum"],
    description: "Crushed velvet mini with ruched sides. Luxe texture, perfect fit. The dress that does everything.",
    details: ["95% Velvet", "Dry clean preferred", "Ruched side detail", "V-neckline", "Midi length"],
    isSale: true,
    rating: 4.8,
    reviewCount: 203,
    tags: ["velvet", "mini", "ruched", "luxe"],
  },
  {
    id: "6",
    slug: "siren-lace-bodysuit",
    name: "Siren Lace Bodysuit",
    price: 65,
    category: "tops",
    images: [
      "https://images.unsplash.com/photo-1487222477894-9536515fb9bc?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Nude"],
    description: "Intricate lace bodysuit with thong back. Wear under high-waisted pants or as a standalone statement piece.",
    details: ["90% Nylon, 10% Spandex", "Hand wash", "Thong back", "Snap closure", "Adjustable straps"],
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 445,
    tags: ["bodysuit", "lace", "black", "sexy"],
  },
  {
    id: "7",
    slug: "neon-nights-set",
    name: "Neon Nights Set",
    price: 109,
    category: "sets",
    images: [
      "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1485897978496-b4a0d2ad6b1e?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Hot Pink", "Neon Green"],
    description: "Matching crop bralette and micro skirt set. Bold, fearless, unforgettable.",
    details: ["100% Stretch Jersey", "Machine wash", "Crop bralette with underwire", "Micro mini skirt", "Sold as set"],
    isNew: true,
    isTrending: true,
    stockCount: 8,
    rating: 4.7,
    reviewCount: 67,
    tags: ["set", "neon", "pink", "matching"],
  },
  {
    id: "8",
    slug: "luxe-gold-blazer-dress",
    name: "Luxe Gold Blazer Dress",
    price: 145,
    category: "dresses",
    images: [
      "https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1581044777550-4cfa68e4e48b?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Gold", "Black"],
    description: "Oversized blazer dress in liquid gold fabric. Power dressing redefined. Belt optional.",
    details: ["100% Metallic Fabric", "Dry clean only", "Oversized cut", "Belt included", "Blazer collar"],
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 178,
    tags: ["blazer", "gold", "metallic", "power"],
  },
  {
    id: "9",
    slug: "shadow-strappy-heels",
    name: "Shadow Strappy Heels",
    price: 79,
    category: "heels",
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    colors: ["Black", "Nude"],
    description: "100mm strappy stiletto heel. Ankle wrap closure. The only heels you need this season.",
    details: ["Faux leather upper", "100mm heel height", "Ankle wrap strap", "Platform: 10mm", "Padded insole"],
    isTrending: true,
    rating: 4.6,
    reviewCount: 312,
    tags: ["heels", "strappy", "stiletto", "black"],
  },
  {
    id: "10",
    slug: "champagne-satin-slip",
    name: "Champagne Satin Slip",
    price: 85,
    category: "dresses",
    images: [
      "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Champagne", "Black", "Nude"],
    description: "Bias-cut satin slip dress. Effortlessly sexy, eternally chic. Midi length with adjustable straps.",
    details: ["100% Satin", "Hand wash cold", "Bias cut", "Adjustable spaghetti straps", "Midi length"],
    isNew: true,
    rating: 4.8,
    reviewCount: 134,
    tags: ["satin", "slip", "midi", "champagne"],
  },
  {
    id: "11",
    slug: "rebel-corset-top",
    name: "Rebel Corset Top",
    price: 75,
    category: "corsets",
    images: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "White"],
    description: "Structured boning meets modern edge. Wear over shirts, with jeans, or let it lead. This corset does it all.",
    details: ["8 steel bones", "Lace-up back", "Hook & eye front", "Cotton lining", "Machine wash on delicate"],
    isBestSeller: true,
    stockCount: 5,
    rating: 4.9,
    reviewCount: 289,
    tags: ["corset", "boned", "structured", "top"],
  },
  {
    id: "12",
    slug: "chrome-crop-top",
    name: "Chrome Crop Top",
    price: 55,
    category: "tops",
    images: [
      "https://images.unsplash.com/photo-1566206091558-7f218b696731?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1529139574466-a303027bc851?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Silver", "Gold", "Black"],
    description: "Metallic woven crop top. TikTok's most wanted. Pairs with everything, outshines everyone.",
    details: ["100% Metallic Weave", "Hand wash cold", "Bralette fit", "Cropped length", "Stretchy waistband"],
    isNew: true,
    isTrending: true,
    stockCount: 12,
    rating: 4.7,
    reviewCount: 445,
    tags: ["crop", "metallic", "silver", "trending"],
  },
  {
    id: "13",
    slug: "obsidian-cutout-dress",
    name: "Obsidian Cutout Dress",
    price: 110,
    category: "clubwear",
    images: [
      "https://images.unsplash.com/photo-1496747611176-887b1138d930?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black"],
    description: "Strategic cutouts, maximum impact. Bodycon silhouette with architectural cutout detailing at waist and hip.",
    details: ["Stretch jersey", "Machine wash cold", "Side cutouts", "Bodycon fit", "Mini length"],
    isBestSeller: true,
    isTrending: true,
    stockCount: 7,
    rating: 4.8,
    reviewCount: 367,
    tags: ["cutout", "bodycon", "black", "clubwear"],
  },
  {
    id: "14",
    slug: "rose-gold-mini-dress",
    name: "Rose Gold Mini Dress",
    price: 99,
    originalPrice: 135,
    category: "dresses",
    images: [
      "https://images.unsplash.com/photo-1487222477894-9536515fb9bc?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose Gold"],
    description: "Rose gold metallic mini with ruched details. The ultimate party dress. Fully lined for comfort.",
    details: ["Metallic jersey", "Hand wash", "Ruched sides", "Fully lined", "Invisible zip"],
    isSale: true,
    rating: 4.7,
    reviewCount: 198,
    tags: ["rose gold", "metallic", "mini", "ruched"],
  },
  {
    id: "15",
    slug: "black-magic-bodysuit",
    name: "Black Magic Bodysuit",
    price: 69,
    category: "tops",
    images: [
      "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1485897978496-b4a0d2ad6b1e?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black"],
    description: "Deep plunge mesh bodysuit with scallop trim. Sheer panels, solid lining. TikTok viral.",
    details: ["Mesh with lining", "Hand wash", "Deep V plunge", "Thong back", "Press stud closure"],
    isNew: true,
    isTrending: true,
    stockCount: 9,
    rating: 4.9,
    reviewCount: 521,
    tags: ["bodysuit", "mesh", "plunge", "viral"],
  },
  {
    id: "16",
    slug: "silver-siren-co-ord",
    name: "Silver Siren Co-Ord",
    price: 129,
    category: "sets",
    images: [
      "https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1581044777550-4cfa68e4e48b?auto=format&fit=crop&w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Silver"],
    description: "Metallic bandeau top and high-waisted micro skirt. The co-ord that breaks the internet. Sold as set.",
    details: ["Metallic fabric", "Hand wash", "Bandeau top with underwire", "Micro mini skirt", "Sold as set"],
    isNew: true,
    isBestSeller: true,
    stockCount: 4,
    rating: 5.0,
    reviewCount: 78,
    tags: ["co-ord", "silver", "metallic", "bandeau"],
  },
];

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);

export const getFeaturedProducts = () =>
  products.filter((p) => p.isBestSeller).slice(0, 8);

export const getNewArrivals = () =>
  products.filter((p) => p.isNew).slice(0, 8);

export const getTrending = () =>
  products.filter((p) => p.isTrending).slice(0, 4);

export const getSaleItems = () =>
  products.filter((p) => p.isSale || (p.originalPrice && p.originalPrice > p.price));

export const categories = [
  { slug: "dresses", label: "Dresses", count: products.filter(p => p.category === "dresses").length },
  { slug: "sets", label: "Sets & Co-Ords", count: products.filter(p => p.category === "sets").length },
  { slug: "tops", label: "Tops & Bodysuits", count: products.filter(p => p.category === "tops").length },
  { slug: "corsets", label: "Corsets", count: products.filter(p => p.category === "corsets").length },
  { slug: "clubwear", label: "Clubwear", count: products.filter(p => p.category === "clubwear").length },
  { slug: "jumpsuits", label: "Jumpsuits", count: products.filter(p => p.category === "jumpsuits").length },
  { slug: "heels", label: "Heels", count: products.filter(p => p.category === "heels").length },
];
